version: '3.9'
services:
  backend:
    container_name: frontend_app
    image: nodeimage
    restart: always
    networks:
      - frontend
    build:
      context: ./
      dockerfile: Dockerfile    
    ports:
      - 5000:5000

networks:
  frontend:
    name: frontend